# NUMPY

In [1]:
import numpy as np

In [2]:
np.array([8,5,6,2])

array([8, 5, 6, 2])

In [3]:
type([8,5,6,2])

list

In [4]:
a=np.array([1,2,3,4,6])
print("type-",a.dtype)
print('\n','*'*50)
print('\n',a)

type- int32

 **************************************************

 [1 2 3 4 6]


In [5]:
a=np.array([1,2,3,4,5,6],dtype=float)

In [6]:
a

array([1., 2., 3., 4., 5., 6.])

In [7]:
a=[1,2,3,4,5]
b=np.array(a)

In [8]:
print(b)

[1 2 3 4 5]


In [9]:
c=np.asarray(b)
print(c)


[1 2 3 4 5]


In [10]:
my_mat=([1,2,3],[4,5,6],[7,8,9])

In [11]:
mat=np.array(my_mat)


In [12]:
print("type\class of the object:",type(mat))
print("dimension of the matrix :",mat.ndim,sep="")
print("size of the matrix :",mat.size,sep="")
print("shape of the matrix :",mat.shape,sep="")
print("datatype of the matrix :",mat.dtype,sep="")
print("Here is the matrix","\n",(mat))


type\class of the object: <class 'numpy.ndarray'>
dimension of the matrix :2
size of the matrix :9
shape of the matrix :(3, 3)
datatype of the matrix :int32
Here is the matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# arange and linspace

# arange

In [13]:
print(a)

[1, 2, 3, 4, 5]


In [14]:
a[::-1]

[5, 4, 3, 2, 1]

In [15]:
print("every 5th numbers from 50 in reverse order \n")
a=np.arange(50,0,-5)
print(a)

every 5th numbers from 50 in reverse order 

[50 45 40 35 30 25 20 15 10  5]


In [16]:
a=np.arange(2,10.5,.3)

In [17]:
a

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,  8.3,
        8.6,  8.9,  9.2,  9.5,  9.8, 10.1, 10.4])

# linspace

In [18]:
print("linear spaced numbers between 1and10 \n**************************")
print(np.linspace(100,50,10))

linear spaced numbers between 1and10 
**************************
[100.          94.44444444  88.88888889  83.33333333  77.77777778
  72.22222222  66.66666667  61.11111111  55.55555556  50.        ]


In [19]:
np.linspace(5,9,num=10,endpoint=False,retstep=True)


(array([5. , 5.4, 5.8, 6.2, 6.6, 7. , 7.4, 7.8, 8.2, 8.6]), 0.4)

In [20]:
np.linspace(2.0,3.0,num=10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [21]:
np.linspace(2.0,3.0,num=10,endpoint=False)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [22]:
np.linspace(2.0,3.0,num=10,endpoint=False,retstep=True)

(array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9]), 0.1)

In [23]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

# matrix creation

In [24]:
print("vectors of zeros\n-------------")
print(np.zeros(10))

vectors of zeros
-------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
print("vectors of zeros \n--------------------------")
print(np.zeros((5,6)))
print("\n-------------------------------------")

vectors of zeros 
--------------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

-------------------------------------


In [26]:
print("matrix of ones \n---------------------------------")
print(np.ones((5,6)))
print("\n---------------------------------------")

matrix of ones 
---------------------------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

---------------------------------------


In [27]:
print("matrix of 5's\n=====================================")
print(5*np.ones((5,6)))

matrix of 5's
[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


# Reshape

In [28]:
x=np.arange(30).reshape(3,10)

In [29]:
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [30]:
 np.arange(64).reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [31]:
print("Here is the int \n==================================================")

np.arange(60).reshape(6,10),print("\n===================================================")


Here is the int 



(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 None)

# Random and generation

In [32]:
import numpy as np

In [33]:
np.random.rand(10,5)

array([[0.31534032, 0.36294602, 0.73717973, 0.47540045, 0.70082295],
       [0.64140222, 0.86237451, 0.83918326, 0.92769003, 0.10233947],
       [0.76059106, 0.38603088, 0.53141168, 0.66865468, 0.36530519],
       [0.21152967, 0.33234458, 0.77242067, 0.1654836 , 0.48200418],
       [0.79488974, 0.03525784, 0.55093827, 0.39570223, 0.30877203],
       [0.05199661, 0.40302776, 0.96411971, 0.87415352, 0.32254697],
       [0.14558291, 0.7339873 , 0.30745141, 0.76349091, 0.59879045],
       [0.93495406, 0.86440631, 0.67207249, 0.26797294, 0.74717905],
       [0.40893687, 0.70683876, 0.25660555, 0.3298783 , 0.59189527],
       [0.09235508, 0.50948263, 0.77062665, 0.8544749 , 0.88766331]])

In [34]:
import random

In [35]:
print("random integers vectors:",np.random.randint(5,20,10))

random integers vectors: [ 5 17 14  9 14 11 18 12 11  6]


In [36]:
np.random.randint(5,20,10)

array([18, 19, 15, 19, 19, 12, 17,  8, 10, 10])

In [37]:
np.random.seed(3)

In [38]:
np.random.rand(5,10)

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695,
        0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ,
        0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774, 0.54464902,
        0.78031476, 0.30636353, 0.22195788, 0.38797126, 0.93638365],
       [0.97599542, 0.67238368, 0.90283411, 0.84575087, 0.37799404,
        0.09221701, 0.6534109 , 0.55784076, 0.36156476, 0.2250545 ],
       [0.40651992, 0.46894025, 0.26923558, 0.29179277, 0.4576864 ,
        0.86053391, 0.5862529 , 0.28348786, 0.27797751, 0.45462208]])

In [39]:
import numpy as np

In [40]:
np.random.seed(4)
print("random under generation")
print(np.random.rand(5,6))

random under generation
[[0.96702984 0.54723225 0.97268436 0.71481599 0.69772882 0.2160895 ]
 [0.97627445 0.00623026 0.25298236 0.43479153 0.77938292 0.19768507]
 [0.86299324 0.98340068 0.16384224 0.59733394 0.0089861  0.38657128]
 [0.04416006 0.95665297 0.43614665 0.94897731 0.78630599 0.8662893 ]
 [0.17316542 0.07494859 0.60074272 0.16797218 0.73338017 0.40844386]]


In [41]:
print("\n randon integer matrix")
print(np.random.randint(1,30,(6,7)))


 randon integer matrix
[[26 19 18 17 18 26 10]
 [28 17 13 24 19 23  4]
 [12 24 25 19  7  8 14]
 [11  8 10 19 24 22 20]
 [17 22 16  5 28 28 12]
 [20  9 26  6  9 28 27]]


# NUMPY CONDITION

In [42]:
salary=np.random.randint(7,70,10)

In [43]:
salary

array([68, 61, 46, 39, 37, 11, 61, 18, 15, 43])

In [44]:
#set minimum and maximum salary using a-min and a-max
np.clip(salary,20,40)

array([40, 40, 40, 39, 37, 20, 40, 20, 20, 40])

In [45]:
np.clip (salary,40,50)

array([50, 50, 46, 40, 40, 40, 50, 40, 40, 43])

In [46]:
r=np.where(salary>50)

In [47]:
r

(array([0, 1, 6], dtype=int64),)

In [48]:
r=np.where(salary<40)

In [49]:
r

(array([3, 4, 5, 7, 8], dtype=int64),)

In [50]:
r=np.where(salary==30)

In [51]:
r

(array([], dtype=int64),)

# Reshaping other ways

In [52]:
import numpy as np

In [53]:
from numpy.random import randint as ri

In [54]:
a=ri(1,99,30)

In [55]:
a

array([32, 41, 18, 79, 10, 54, 69, 63, 60,  4,  5, 40, 55, 71, 41, 97, 68,
       54, 23, 18, 28, 98, 61, 44, 87, 16, 14,  1, 11,  8])

In [56]:
a.ndim

1

In [57]:
c=ri(1,99,(30))

In [58]:
c

array([64, 80, 60, 53, 53, 65, 88, 98, 47, 43, 50, 32, 36, 31, 66,  4, 87,
       75, 21, 81,  8, 52, 11, 42, 87, 16, 42,  4, 75, 24])

In [59]:
c.ndim

1

In [60]:
d=c.reshape(3,10)

In [61]:
d

array([[64, 80, 60, 53, 53, 65, 88, 98, 47, 43],
       [50, 32, 36, 31, 66,  4, 87, 75, 21, 81],
       [ 8, 52, 11, 42, 87, 16, 42,  4, 75, 24]])

In [62]:
d.reshape(10,3)

array([[64, 80, 60],
       [53, 53, 65],
       [88, 98, 47],
       [43, 50, 32],
       [36, 31, 66],
       [ 4, 87, 75],
       [21, 81,  8],
       [52, 11, 42],
       [87, 16, 42],
       [ 4, 75, 24]])

In [63]:
d=c.reshape(2,3,5)

In [64]:
d

array([[[64, 80, 60, 53, 53],
        [65, 88, 98, 47, 43],
        [50, 32, 36, 31, 66]],

       [[ 4, 87, 75, 21, 81],
        [ 8, 52, 11, 42, 87],
        [16, 42,  4, 75, 24]]])

In [65]:
d=c.reshape(2,3,5)

In [66]:
d

array([[[64, 80, 60, 53, 53],
        [65, 88, 98, 47, 43],
        [50, 32, 36, 31, 66]],

       [[ 4, 87, 75, 21, 81],
        [ 8, 52, 11, 42, 87],
        [16, 42,  4, 75, 24]]])

In [67]:
d.ndim

3

# sorting

In [68]:
j=ri(1,100,25).reshape(5,5)
print("\n 5*5 matrix of random integers\n",'-'*50,"\n",j)


 5*5 matrix of random integers
 -------------------------------------------------- 
 [[ 8 53 29 76 65]
 [38 33 26 38  6]
 [74 75 25 30 94]
 [37 62  3 20 81]
 [23 29 77 17 52]]


In [69]:
print("\n here is the sorted matrix along each row\n",'-'*50,"\n",np.sort(j))


 here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 8 29 53 65 76]
 [ 6 26 33 38 38]
 [25 30 74 75 94]
 [ 3 20 37 62 81]
 [17 23 29 52 77]]


In [70]:
print("\n here is the sorted matrix along each coloumn\n",'-'*50,"\n",np.sort(j))


 here is the sorted matrix along each coloumn
 -------------------------------------------------- 
 [[ 8 29 53 65 76]
 [ 6 26 33 38 38]
 [25 30 74 75 94]
 [ 3 20 37 62 81]
 [17 23 29 52 77]]


# Indexing and Slicing 

In [71]:
arr=np.arange(13,30)
print("array:",arr)


array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [72]:
print("Elemrnt of the 7th index is:",arr[7])

Elemrnt of the 7th index is: 20


In [73]:
arr[0]

13

# SERIES OF VALUES

In [74]:
print("elemnt from 3rd to 5th index are:",arr[3:6])

elemnt from 3rd to 5th index are: [16 17 18]


In [75]:
print("elements after the 4th index are:",arr[4:])

elements after the 4th index are: [17 18 19 20 21 22 23 24 25 26 27 28 29]


# NEGETIVE INDEX

In [76]:
arr

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [77]:
print("elemnets from last backwards are:",arr[-1::-2])

elemnets from last backwards are: [29 27 25 23 21 19 17 15 13]


In [78]:
arr[-1:-6]

array([], dtype=int32)

In [79]:
arr[-6:-1]

array([24, 25, 26, 27, 28])

In [80]:
arr[-2::-3]

array([28, 25, 22, 19, 16, 13])

In [81]:
arr[-1:-8:-1]

array([29, 28, 27, 26, 25, 24, 23])

In [82]:
arr[-3:-16:-3]

array([27, 24, 21, 18, 15])

In [83]:
arr=np.arange(0,21,2)

In [84]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [85]:
print("elements at 2nd,4th and 9th index are:",arr[[2,4,9]])

elements at 2nd,4th and 9th index are: [ 4  8 18]


In [86]:
my_mat=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [87]:
mat=np.array(my_mat)

In [88]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
print("\ndouble bracket indexing \n-----------------------------------------")
print("element in row index 1and coloumn index 2:",mat[1][2])


double bracket indexing 
-----------------------------------------
element in row index 1and coloumn index 2: 7


In [90]:
print("\ndouble bracket indexing \n-----------------------------------------")
print("element in row index 1and coloumn index 2:",mat[2][2])


double bracket indexing 
-----------------------------------------
element in row index 1and coloumn index 2: 11


In [91]:
print("elements in row index 1 and coloumn index 2:", mat[2][3])

elements in row index 1 and coloumn index 2: 12


In [92]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
mat[2]

array([ 9, 10, 11, 12])

In [94]:
mat[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [95]:
mat[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
mat[1:2,1:2]

array([[6]])

In [97]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
mat[0:2,(1,2)]

array([[2, 3],
       [6, 7]])

In [99]:
mat[1:3,(2,3)]

array([[ 7,  8],
       [11, 12]])

# update matrix

In [100]:
print('original matrix \n \n',mat)

original matrix 
 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [101]:
mat[0,1]=40

In [102]:
mat

array([[ 1, 40,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
mat[1,0]=50

In [104]:
mat

array([[ 1, 40,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

# subseting

In [105]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print("matrix of random 2-digit numbers \n========================================"),mat

matrix of random 2-digit numbers 


(None,
 array([[86, 86, 37, 50, 48],
        [89, 61, 72, 17, 37],
        [99, 87, 59, 14, 13]]))

In [106]:
abc=mat[mat<70]

In [107]:
abc

array([37, 50, 48, 61, 17, 37, 59, 14, 13])

In [108]:
abc=mat[mat>70]

In [109]:
abc

array([86, 86, 89, 72, 99, 87])

In [110]:
print("elements greaterthan 50\n",mat[mat>50])

elements greaterthan 50
 [86 86 89 61 72 99 87 59]


In [111]:
mat>50

array([[ True,  True, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False]])

In [112]:
print(np.where(mat==58))

(array([], dtype=int64), array([], dtype=int64))


# UNIVERSAL FUNCTION

In [113]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
print("\n matrix of random single digit numbers\n==========================================\n",mat1)


 matrix of random single digit numbers
 [[1 3 5]
 [7 2 1]
 [4 2 3]]


In [114]:
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("\n matrix of random single digit numbers\n===============================================\n",mat2)


 matrix of random single digit numbers
 [[4 3 6]
 [3 8 6]
 [7 6 7]]


In [115]:
print("\n ADITION\n====================\n",mat1+mat2)


 ADITION
 [[ 5  6 11]
 [10 10  7]
 [11  8 10]]


In [116]:
print("\n SUBSTRACTION\n===============================\n",mat1-mat2)


 SUBSTRACTION
 [[-3  0 -1]
 [ 4 -6 -5]
 [-3 -4 -4]]


In [117]:
print("\n multiplication \n============================\n",mat1*mat2)


 multiplication 
 [[ 4  9 30]
 [21 16  6]
 [28 12 21]]


In [118]:
print("\n DIVISION \n==================================\n",mat1/mat2)


 DIVISION 
 [[0.25       1.         0.83333333]
 [2.33333333 0.25       0.16666667]
 [0.57142857 0.33333333 0.42857143]]


In [119]:
print("\n LINEAR COMBINATION :3*MAT1-2*MAT2\n=====================================================\n",3*mat1-2*mat2)


 LINEAR COMBINATION :3*MAT1-2*MAT2
 [[ -5   3   3]
 [ 15 -10  -9]
 [ -2  -6  -5]]


# BROADCASTING

In [123]:
start=np.zeros((3,3))

In [139]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [153]:
# create a rank 1 ndarray with 3 values
add_rows=np.array([[[1,0,2]]])

In [154]:
print(add_rows)

[[[1 0 2]]]


In [155]:
y=start+add_rows    # add to each row of 'start' using with broadcasting

In [156]:
print(y)

[[[1. 0. 2.]
  [1. 0. 2.]
  [1. 0. 2.]]]


In [157]:
y= start+add_rows.T

In [158]:
print(y)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [159]:
z=add_rows.T

In [160]:
z

array([[[1]],

       [[0]],

       [[2]]])

In [163]:
add_cols=np.array([[0,1,2,3]])

In [164]:
print(add_cols)

[[0 1 2 3]]


In [165]:
add_cols=add_cols.T

In [166]:
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


# ARRAY MATH

In [167]:
mat1

array([[1, 3, 5],
       [7, 2, 1],
       [4, 2, 3]])

In [168]:
print("\n sqrt of the 1st matrix  using np\n=================================================\n",np.sqrt(mat1))


 sqrt of the 1st matrix  using np
 [[1.         1.73205081 2.23606798]
 [2.64575131 1.41421356 1.        ]
 [2.         1.41421356 1.73205081]]


In [169]:
print("\n square of the 1st mstrix using np\n==================================================\n",np.square(mat1))


 square of the 1st mstrix using np
 [[ 1  9 25]
 [49  4  1]
 [16  4  9]]
